// Raw mocap poses do not survive a flat silhouette.
//
// A real dancer's hand passing in front of his own head still reads, because
// a photograph has edges and shading. Our man is one solid black shape, so a
// hand near his head simply disappears into it. This pass swings any buried
// limb outward until its own silhouette clears the parts behind it — the
// smallest change that makes the pose legible.
//
// It uses the renderer's own solve() rather than a second copy of the maths,
// so it cannot drift out of agreement with what actually gets drawn.

import { readFileSync, writeFileSync } from 'fs';
import { solve, NEUTRAL } from '../src/figure.js';
import { DANCER } from '../src/character.js';

const ST = { ...DANCER, scale: 1 };
const raw = JSON.parse(readFileSync(process.argv[2], 'utf8'));

// Screen-space gap between two joints' drawn discs. Negative means they merge.
function gap(J, a, ra, b, rb) {
  const d = Math.hypot(J[a][0] - J[b][0], J[a][1] - J[b][1]);
  return d - (DANCER.thick[ra] * J[a][2] + DANCER.thick[rb] * J[b][2]);
}

// Each arm is swung outward: his left is local -x, so outward is a more
// negative yaw on the left and a more positive one on the right.
const ARMS = [
  { side: -1, up: 'armLU', fore: 'armLF', wrist: 'wristL', elbow: 'elbowL' },
  { side: +1, up: 'armRU', fore: 'armRF', wrist: 'wristR', elbow: 'elbowR' },
];

function declutter(pose) {
  const p = { ...NEUTRAL, ...pose };
  for (const arm of ARMS) {
    for (let i = 0; i < 24; i++) {
      const J = solve(ST, p);
      // Clear the head, and clear the torso the hand would otherwise vanish into.
      const worst = Math.min(
        gap(J, arm.wrist, 'wrist', 'head', 'head'),
        gap(J, arm.elbow, 'elbow', 'head', 'head'),
        gap(J, arm.wrist, 'wrist', 'chestTop', 'chest'),
      );
      if (worst > 2) break;
      p[arm.up + 'Y'] += arm.side * 4;
      p[arm.fore + 'Y'] += arm.side * 4;
    }
  }
  return p;
}

// A name from the shape itself: how high the arms are, and how wide.
function classify(poses) {
  const avg = (f) => poses.reduce((s, q) => s + f(q), 0) / poses.length;
  const pitch = avg((q) => (q.armLU + q.armRU) / 2);
  const spread = avg((q) => (Math.abs(q.armLUY) + Math.abs(q.armRUY)) / 2);
  const height = pitch < -25 ? 'high' : pitch < 35 ? 'mid' : 'low';
  const width = spread > 78 ? 'Wide' : spread > 45 ? 'Open' : 'Tight';
  return height + width;
}

const seen = {};
const moves = raw.moves.map((m) => {
  const poses = m.poses.map(declutter);
  let name = classify(poses);
  seen[name] = (seen[name] || 0) + 1;
  if (seen[name] > 1) name += seen[name];
  return { name, from: `dancer ${m.who} at ${m.t.toFixed(2)}s`, poses };
});

const round = (v) => Math.round(v * 10) / 10;
const KEYS = ['turn', 'headTurn', 'headPitch',
              'armLU', 'armLUY', 'armLF', 'armLFY', 'armRU', 'armRUY', 'armRF', 'armRFY',
              'legLU', 'legLUY', 'legLF', 'legLFY', 'legRU', 'legRUY', 'legRF', 'legRFY'];

const body = moves.map((m) => {
  const rows = m.poses.map((p) => '      { ' + KEYS.map((k) => `${k}: ${round(p[k])}`).join(', ') + ' },');
  return `  {\n    name: '${m.name}',\n    from: '${m.from}',\n    poses: [\n${rows.join('\n')}\n    ],\n  },`;
}).join('\n');

writeFileSync('src/moves.js', `// Dance moves lifted off the reference video.
//
// Each move is ${raw.beats_per_move} target poses, one per beat. The rig's springs generate
// every frame between them — including the follow-through — so there is no
// per-frame animation data here and none is needed.
//
// Captured with MediaPipe at ${raw.source_bpm} BPM and retargeted into the rig's own
// body frame, which is why they replay at any tempo: a move is a sequence of
// shapes, not a recording.
//
// Every pose has been through the declutter pass in tools/declutter.mjs. A
// real dancer's hand can pass in front of his own face and still read; a solid
// black silhouette cannot, so buried limbs are swung out until they clear.
//
// Generated by tools/build_moves.py and tools/declutter.mjs. Edit the tools,
// or hand-tune a pose here and it will stay tuned.

export const BEATS_PER_MOVE = ${raw.beats_per_move};

export const MOVES = [
${body}
];

export const MOVE_BY_NAME = Object.fromEntries(MOVES.map((m) => [m.name, m]));
`);

console.log(`wrote src/moves.js — ${moves.length} moves`);
for (const m of moves) console.log(`  ${m.name.padEnd(10)} ${m.from}`);
