// Dance moves lifted off the reference video.
//
// Each move is 4 target poses, one per beat. The rig's springs generate
// every frame between them — including the follow-through — so there is no
// per-frame animation data here and none is needed.
//
// Captured with MediaPipe at 133 BPM and retargeted into the rig's own
// body frame, which is why they replay at any tempo: a move is a sequence of
// shapes, not a recording.
//
// Every pose has been through the declutter pass in tools/declutter.mjs. A
// real dancer's hand can pass in front of his own face and still read; a solid
// black silhouette cannot, so buried limbs are swung out until they clear.
//
// Generated by tools/build_moves.py and tools/declutter.mjs. Edit the tools,
// or hand-tune a pose here and it will stay tuned.

export const BEATS_PER_MOVE = 4;

export const MOVES = [
  {
    name: 'lowOpen',
    from: 'dancer 0 at 9.20s',
    poses: [
      { turn: -66, headTurn: -9.4, headPitch: 7.9, armLU: 29.3, armLUY: -16.3, armLF: 10.6, armLFY: 34.6, armRU: 85.5, armRUY: -55, armRF: 69.4, armRFY: -46.2, legLU: 78.7, legLUY: -155.7, legLF: 58.9, legLFY: 132, legRU: 71.3, legRUY: 165.6, legRF: 69.2, legRFY: 115.9 },
      { turn: -17, headTurn: 19.6, headPitch: -0.7, armLU: -72.2, armLUY: -143.7, armLF: -36.3, armLFY: -2, armRU: 36.7, armRUY: 44.3, armRF: 2.6, armRFY: 44, legLU: 81, legLUY: -56.2, legLF: 57.5, legLFY: 173.3, legRU: 74, legRUY: -76.5, legRF: 74.8, legRFY: 150.1 },
      { turn: -16.2, headTurn: -4, headPitch: 13.9, armLU: 55.3, armLUY: -59.1, armLF: 58.6, armLFY: -9, armRU: 59.5, armRUY: 42.5, armRF: 5, armRFY: 36.2, legLU: 82.6, legLUY: -103.9, legLF: 58.8, legLFY: 164.9, legRU: 73.3, legRUY: -144.3, legRF: 63.6, legRFY: 149.2 },
      { turn: -9, headTurn: -17.3, headPitch: 12, armLU: 61.9, armLUY: -37.6, armLF: 67.7, armLFY: -12.5, armRU: 36.2, armRUY: 51.7, armRF: 4, armRFY: 57, legLU: 80.3, legLUY: -72.1, legLF: 71.2, legLFY: 173.6, legRU: 75.2, legRUY: -132.6, legRF: 64.6, legRFY: 148.6 },
    ],
  },
  {
    name: 'midWide',
    from: 'dancer 1 at 14.16s',
    poses: [
      { turn: -11.5, headTurn: -5.4, headPitch: 8.2, armLU: 62.5, armLUY: -82.3, armLF: 66, armLFY: -79, armRU: 64.9, armRUY: 34.7, armRF: 38, armRFY: 33.8, legLU: 80.7, legLUY: -54.2, legLF: 64.2, legLFY: 172.5, legRU: 85.8, legRUY: -103, legRF: 71.1, legRFY: 165.3 },
      { turn: -19.3, headTurn: 1.8, headPitch: -34, armLU: 52, armLUY: 47.4, armLF: 2, armLFY: 83.9, armRU: -68.1, armRUY: 123, armRF: -33.4, armRFY: -52.5, legLU: 75.8, legLUY: -141.9, legLF: 56.2, legLFY: 172.7, legRU: 81.1, legRUY: -144.2, legRF: 51.7, legRFY: 159.1 },
      { turn: -28.2, headTurn: 12.4, headPitch: -4.4, armLU: -55.2, armLUY: -220.6, armLF: -35.5, armLFY: 41.7, armRU: -31, armRUY: 106.6, armRF: -53.8, armRFY: 145.8, legLU: 79.3, legLUY: -127.6, legLF: 51.7, legLFY: 166, legRU: 79.9, legRUY: -171.3, legRF: 53.5, legRFY: 155.7 },
      { turn: -14.2, headTurn: 1.7, headPitch: -8.9, armLU: -77.9, armLUY: -128, armLF: -21.5, armLFY: 42.3, armRU: -54.9, armRUY: 170.7, armRF: -43.3, armRFY: -52.7, legLU: 84.1, legLUY: -141.2, legLF: 53.6, legLFY: 176.3, legRU: 80.6, legRUY: 179, legRF: 61.4, legRFY: 160 },
    ],
  },
  {
    name: 'lowWide',
    from: 'dancer 1 at 16.87s',
    poses: [
      { turn: -45.6, headTurn: 50.1, headPitch: 0.7, armLU: 4, armLUY: -192.5, armLF: 23.2, armLFY: -215.7, armRU: 6.6, armRUY: 78.3, armRF: -66.6, armRFY: 144.9, legLU: 77.5, legLUY: -11.6, legLF: 67.5, legLFY: 136.5, legRU: 72.2, legRUY: 12.7, legRF: 82.5, legRFY: 78.4 },
      { turn: 36.3, headTurn: -3, headPitch: -20, armLU: 70.2, armLUY: -122.9, armLF: 72.2, armLFY: -124.2, armRU: 54, armRUY: -14.7, armRF: 3.1, armRFY: -41.6, legLU: 86.3, legLUY: -108.5, legLF: 59.2, legLFY: -152.6, legRU: 85.1, legRUY: -169.9, legRF: 55.3, legRFY: -166.7 },
      { turn: 77.1, headTurn: -18.6, headPitch: -22.1, armLU: 38.9, armLUY: -27.2, armLF: -13.5, armLFY: -44.6, armRU: 42.2, armRUY: -3.3, armRF: -13.6, armRFY: -93.8, legLU: 78.3, legLUY: -6.1, legLF: 64.4, legLFY: -100.7, legRU: 76.1, legRUY: -115.1, legRF: 58.9, legRFY: -121.7 },
      { turn: 17, headTurn: -17.2, headPitch: -7.8, armLU: 84, armLUY: -108.6, armLF: -6.4, armLFY: -23.7, armRU: 64.4, armRUY: 78.9, armRF: 14.5, armRFY: -36.5, legLU: 83.8, legLUY: -71.7, legLF: 56.5, legLFY: -162.4, legRU: 84.5, legRUY: -149, legRF: 52.4, legRFY: -172.3 },
    ],
  },
  {
    name: 'highOpen',
    from: 'dancer 0 at 17.32s',
    poses: [
      { turn: 14, headTurn: -2.8, headPitch: 25, armLU: -60.5, armLUY: -41.7, armLF: -66.8, armLFY: 19.8, armRU: -21.8, armRUY: 42.2, armRF: -87.9, armRFY: -71.8, legLU: 76.8, legLUY: -81.7, legLF: 69.1, legLFY: -158.1, legRU: 68, legRUY: -99.5, legRF: 68.7, legRFY: 174.9 },
      { turn: -6.8, headTurn: -1, headPitch: 18.7, armLU: -41.8, armLUY: -105.8, armLF: -65, armLFY: -29.5, armRU: -12.1, armRUY: 41.5, armRF: -61.2, armRFY: 42.4, legLU: 83.1, legLUY: -65.7, legLF: 66.2, legLFY: -172, legRU: 76.2, legRUY: -146.9, legRF: 68.8, legRFY: 158.6 },
      { turn: -14, headTurn: -9, headPitch: 9.2, armLU: -79.8, armLUY: -74.1, armLF: -59.9, armLFY: 36.8, armRU: -52.6, armRUY: 122, armRF: -78.1, armRFY: -76.7, legLU: 78.6, legLUY: -82.3, legLF: 60.7, legLFY: 170.4, legRU: 80.1, legRUY: -126.9, legRF: 64, legRFY: 152.1 },
      { turn: 2.5, headTurn: 4.3, headPitch: 7.9, armLU: 34.7, armLUY: -60.7, armLF: -18.4, armLFY: -30.3, armRU: 28.1, armRUY: 34.1, armRF: -41.3, armRFY: -5.5, legLU: 74.8, legLUY: -41.3, legLF: 68.1, legLFY: -164.2, legRU: 74.2, legRUY: -67.1, legRF: 61.4, legRFY: 174.1 },
    ],
  },
  {
    name: 'lowOpen2',
    from: 'dancer 1 at 19.13s',
    poses: [
      { turn: -26.7, headTurn: -8.6, headPitch: 5.4, armLU: 73, armLUY: 8.7, armLF: 15.1, armLFY: 61.4, armRU: 65.9, armRUY: 12.8, armRF: 8, armRFY: 12.1, legLU: 80.5, legLUY: -100.8, legLF: 53.8, legLFY: 167.5, legRU: 77, legRUY: -55.7, legRF: 63.1, legRFY: 159.9 },
      { turn: -8.7, headTurn: -11.9, headPitch: 23.9, armLU: 66.6, armLUY: -69.9, armLF: 63.9, armLFY: -60.2, armRU: 47.5, armRUY: 10.3, armRF: -8.3, armRFY: 8.9, legLU: 75.3, legLUY: -23.3, legLF: 74.8, legLFY: 176, legRU: 66.8, legRUY: -29.1, legRF: 83.5, legRFY: 102.5 },
      { turn: 9.3, headTurn: 5.5, headPitch: -2.4, armLU: 73.5, armLUY: -170.5, armLF: 70.6, armLFY: -137.7, armRU: 79.9, armRUY: 83.7, armRF: 79.5, armRFY: -21, legLU: 80.8, legLUY: -35.1, legLF: 62.8, legLFY: 176.1, legRU: 81.7, legRUY: -150.4, legRF: 57.3, legRFY: 174.3 },
      { turn: -7.8, headTurn: -2.3, headPitch: 19.5, armLU: 74.7, armLUY: -97.9, armLF: 79.5, armLFY: -83.4, armRU: 71, armRUY: 4.4, armRF: 57.6, armRFY: -2.5, legLU: 72.9, legLUY: -29.6, legLF: 67.6, legLFY: -175.2, legRU: 80.7, legRUY: -1.3, legRF: 75.2, legRFY: 166.1 },
    ],
  },
  {
    name: 'lowWide2',
    from: 'dancer 1 at 20.93s',
    poses: [
      { turn: -1.2, headTurn: -3, headPitch: 2.3, armLU: 67.8, armLUY: -122.5, armLF: 83, armLFY: -151.5, armRU: 50.4, armRUY: 10.8, armRF: -5.5, armRFY: 5.4, legLU: 80.6, legLUY: 50.4, legLF: 63, legLFY: 161.2, legRU: 74.4, legRUY: 83.3, legRF: 54.9, legRFY: 152.7 },
      { turn: -2.8, headTurn: -3.6, headPitch: 6.3, armLU: 69, armLUY: -137.6, armLF: 76.8, armLFY: -128.5, armRU: 58.2, armRUY: 34.5, armRF: -11.5, armRFY: -20.7, legLU: 82.9, legLUY: -107.8, legLF: 49.3, legLFY: -177, legRU: 80.8, legRUY: -8.8, legRF: 58.6, legRFY: 172.4 },
      { turn: -8.5, headTurn: -6.5, headPitch: 8.9, armLU: 75.2, armLUY: -122.6, armLF: 73, armLFY: -150.2, armRU: 22.9, armRUY: 82, armRF: -59.8, armRFY: -18.7, legLU: 81.9, legLUY: 19.6, legLF: 65.8, legLFY: 166.6, legRU: 72.2, legRUY: 87.4, legRF: 53.1, legRFY: 165.2 },
      { turn: 27.9, headTurn: -21.9, headPitch: -12.8, armLU: 71.8, armLUY: -114.4, armLF: 72.5, armLFY: -91.5, armRU: 60.9, armRUY: -7.7, armRF: 3.1, armRFY: -37.3, legLU: 84.1, legLUY: -55.7, legLF: 61.6, legLFY: -151, legRU: 83.7, legRUY: 139.4, legRF: 55.2, legRFY: -162.8 },
    ],
  },
  {
    name: 'lowOpen3',
    from: 'dancer 1 at 23.19s',
    poses: [
      { turn: -18.4, headTurn: -10, headPitch: 8.2, armLU: 63.3, armLUY: -13.5, armLF: -40.7, armLFY: -22.1, armRU: 75.1, armRUY: 111.2, armRF: 61.8, armRFY: 45.8, legLU: 76.9, legLUY: -83.7, legLF: 58.9, legLFY: 168.2, legRU: 88, legRUY: -81.1, legRF: 57.6, legRFY: 162.6 },
      { turn: -17.3, headTurn: -0.2, headPitch: -2.2, armLU: 32, armLUY: -66.8, armLF: 4.9, armLFY: 45, armRU: 80.5, armRUY: 148.7, armRF: 70.9, armRFY: 68.5, legLU: 83.8, legLUY: -49.2, legLF: 58.6, legLFY: 166.8, legRU: 89, legRUY: 5.5, legRF: 57.9, legRFY: 162 },
      { turn: -24.4, headTurn: -5.5, headPitch: 10.6, armLU: -15.6, armLUY: -38.3, armLF: -49.8, armLFY: 1.7, armRU: 86, armRUY: -3, armRF: 73.9, armRFY: 51.6, legLU: 76.2, legLUY: -91.4, legLF: 52.7, legLFY: 172.7, legRU: 80.3, legRUY: -101.5, legRF: 60.1, legRFY: 161.5 },
      { turn: -11.3, headTurn: -4.8, headPitch: -0.8, armLU: 47, armLUY: -73.7, armLF: 10.4, armLFY: 64.1, armRU: 84.1, armRUY: 94.1, armRF: 73.2, armRFY: 43.6, legLU: 81.2, legLUY: -61.2, legLF: 56.6, legLFY: 171.5, legRU: 82, legRUY: -2.8, legRF: 63.1, legRFY: 164.2 },
    ],
  },
  {
    name: 'lowOpen4',
    from: 'dancer 0 at 23.64s',
    poses: [
      { turn: -64.5, headTurn: 21.2, headPitch: 8.4, armLU: 59.2, armLUY: -29.2, armLF: -26, armLFY: 49.2, armRU: 79.1, armRUY: -84.2, armRF: 12.7, armRFY: -22.6, legLU: 76.3, legLUY: 171.4, legLF: 54, legLFY: 136.4, legRU: 71.7, legRUY: 135.5, legRF: 66.8, legRFY: 111.2 },
      { turn: -19.5, headTurn: -2.7, headPitch: 4.5, armLU: 14.2, armLUY: -41, armLF: -57.1, armLFY: 26.9, armRU: 80.4, armRUY: 148.4, armRF: 73.2, armRFY: 79.4, legLU: 73.8, legLUY: -111.1, legLF: 49.5, legLFY: 175.6, legRU: 79, legRUY: -142.9, legRF: 52, legRFY: 164.5 },
      { turn: -60.2, headTurn: -6.8, headPitch: 8.7, armLU: 54.4, armLUY: -28.6, armLF: -37.2, armLFY: 32.8, armRU: 87.8, armRUY: -13.5, armRF: 13, armRFY: -1, legLU: 86.1, legLUY: -177.5, legLF: 59.8, legLFY: 129.4, legRU: 79.6, legRUY: 152.9, legRF: 68.8, legRFY: 105.9 },
      { turn: -26.5, headTurn: 22.8, headPitch: 5.7, armLU: 54.1, armLUY: -75.5, armLF: -13, armLFY: 32.9, armRU: 68.4, armRUY: -26.1, armRF: -14.5, armRFY: -6.7, legLU: 81.1, legLUY: -71.7, legLF: 61.8, legLFY: 162.2, legRU: 78, legRUY: -156.6, legRF: 66.6, legRFY: 141.8 },
    ],
  },
  {
    name: 'midWide2',
    from: 'dancer 1 at 24.99s',
    poses: [
      { turn: -3.7, headTurn: 0.5, headPitch: 1.4, armLU: 53.6, armLUY: -56.9, armLF: -0.1, armLFY: 14, armRU: 69.7, armRUY: 19.5, armRF: -11.8, armRFY: -16.3, legLU: 83.9, legLUY: -94.3, legLF: 51, legLFY: 179.5, legRU: 82.9, legRUY: -40.9, legRF: 59.2, legRFY: 167 },
      { turn: -4.2, headTurn: 1, headPitch: -3, armLU: 52.1, armLUY: -70.9, armLF: -16.3, armLFY: 32.6, armRU: 67.7, armRUY: 28.3, armRF: -17.2, armRFY: -12.6, legLU: 84.9, legLUY: -90.1, legLF: 46.1, legLFY: 177.5, legRU: 84.4, legRUY: 86, legRF: 47.7, legRFY: 168.8 },
      { turn: -8.1, headTurn: -0.7, headPitch: 2.4, armLU: -24.8, armLUY: -183.7, armLF: -21.5, armLFY: 40, armRU: -10.8, armRUY: 86.2, armRF: -47.5, armRFY: -173.7, legLU: 81.8, legLUY: -119.5, legLF: 54.5, legLFY: -176.9, legRU: 86.8, legRUY: 132.2, legRF: 59.1, legRFY: 169.8 },
      { turn: -11, headTurn: -2.4, headPitch: -1.6, armLU: -0.4, armLUY: -182.5, armLF: -5.4, armLFY: 3.8, armRU: 44.1, armRUY: 49, armRF: -23.5, armRFY: -6.4, legLU: 82, legLUY: -107.8, legLF: 54.7, legLFY: 177.5, legRU: 88.5, legRUY: -130.7, legRF: 59.5, legRFY: 168.7 },
    ],
  },
  {
    name: 'lowWide3',
    from: 'dancer 1 at 28.15s',
    poses: [
      { turn: -12.1, headTurn: -7.6, headPitch: 8, armLU: 4.6, armLUY: -68.2, armLF: 0.1, armLFY: -16.9, armRU: 60.7, armRUY: 27.2, armRF: 3.6, armRFY: 28.1, legLU: 78.8, legLUY: -58.4, legLF: 57.1, legLFY: -179.9, legRU: 83.1, legRUY: -69.5, legRF: 68.6, legRFY: 160.8 },
      { turn: -6.5, headTurn: -1.9, headPitch: 4.7, armLU: 83.9, armLUY: 161.8, armLF: 10.7, armLFY: 92.7, armRU: 76.2, armRUY: -10.1, armRF: 7.2, armRFY: -69.5, legLU: 82.2, legLUY: -107.4, legLF: 51.9, legLFY: -175.8, legRU: 87.6, legRUY: -99.2, legRF: 58.5, legRFY: 172.5 },
      { turn: -2.8, headTurn: -0.2, headPitch: 8.3, armLU: 69.4, armLUY: -174.5, armLF: 61.9, armLFY: -170.2, armRU: 85.1, armRUY: -163.3, armRF: 78.7, armRFY: 167.5, legLU: 81.5, legLUY: -51.4, legLF: 61.4, legLFY: -171.5, legRU: 82.2, legRUY: -110.5, legRF: 60.9, legRFY: 175.8 },
      { turn: -10.7, headTurn: -3.1, headPitch: 4.5, armLU: 24.5, armLUY: -104.7, armLF: 42.8, armLFY: -158.4, armRU: 49.9, armRUY: 82.1, armRF: 8.8, armRFY: 61.1, legLU: 79.2, legLUY: -80.5, legLF: 55.9, legLFY: 171.9, legRU: 84.9, legRUY: -125.9, legRF: 61.8, legRFY: 165.1 },
    ],
  },
  {
    name: 'midTight',
    from: 'dancer 1 at 33.11s',
    poses: [
      { turn: 29.9, headTurn: 23.1, headPitch: -5.7, armLU: 66.7, armLUY: -98.6, armLF: 67.4, armLFY: -89.4, armRU: 52.8, armRUY: -41.1, armRF: 28.8, armRFY: -51.3, legLU: 77.3, legLUY: -63.4, legLF: 60.6, legLFY: -149.1, legRU: 79.1, legRUY: -137.4, legRF: 56.4, legRFY: -161.1 },
      { turn: -45.9, headTurn: -17.9, headPitch: -5.7, armLU: 29.6, armLUY: 20.2, armLF: -0.5, armLFY: 54.8, armRU: 66.3, armRUY: -1.3, armRF: -0.6, armRFY: -48.2, legLU: 84.2, legLUY: 178.8, legLF: 61.3, legLFY: 140.5, legRU: 80, legRUY: 69, legRF: 64, legRFY: 133.5 },
      { turn: 8.2, headTurn: 11, headPitch: -2.2, armLU: 28.1, armLUY: -31.4, armLF: -8.7, armLFY: -26.5, armRU: 40.9, armRUY: -3.9, armRF: -3.8, armRFY: -11.8, legLU: 84.2, legLUY: -51.4, legLF: 57.7, legLFY: -171, legRU: 83.1, legRUY: 178.6, legRF: 54.8, legRFY: 175.8 },
      { turn: 91.7, headTurn: 29.6, headPitch: -0.7, armLU: -18.7, armLUY: -108.2, armLF: -64.4, armLFY: -177.7, armRU: 8.2, armRUY: 12.8, armRF: -1.3, armRFY: -81.9, legLU: 71.5, legLUY: -143.8, legLF: 63.3, legLFY: -112.8, legRU: 73.2, legRUY: -42.2, legRF: 65.1, legRFY: -105.6 },
    ],
  },
  {
    name: 'lowTight',
    from: 'dancer 0 at 34.92s',
    poses: [
      { turn: -44.4, headTurn: -3.2, headPitch: 9.1, armLU: 10.1, armLUY: 5.4, armLF: -5.2, armLFY: 56.6, armRU: 42.8, armRUY: 15.9, armRF: -14.7, armRFY: -17.4, legLU: 80.9, legLUY: -159.2, legLF: 59.6, legLFY: 157, legRU: 66.2, legRUY: 153.8, legRF: 65.2, legRFY: 130 },
      { turn: -69.6, headTurn: -16.3, headPitch: 11.7, armLU: 62.9, armLUY: -61.9, armLF: 53.9, armLFY: 30.7, armRU: 79.3, armRUY: -16.3, armRF: 42.9, armRFY: -34.4, legLU: 80.5, legLUY: 120.8, legLF: 57.6, legLFY: 129, legRU: 61.2, legRUY: 120, legRF: 73.1, legRFY: 105.6 },
      { turn: -8.7, headTurn: 9, headPitch: 6.3, armLU: 38.5, armLUY: -65, armLF: 27.1, armLFY: 59.3, armRU: 40.8, armRUY: -41.5, armRF: -17.2, armRFY: -63.5, legLU: 86, legLUY: -43.8, legLF: 55.7, legLFY: 179.6, legRU: 70.3, legRUY: 176.6, legRF: 58.4, legRFY: 159.1 },
      { turn: 15.6, headTurn: 3.8, headPitch: 1.7, armLU: 49.3, armLUY: -55.1, armLF: -19.4, armLFY: 0.6, armRU: 55.3, armRUY: 7.9, armRF: -16.8, armRFY: -22.7, legLU: 86.5, legLUY: -129.2, legLF: 57.6, legLFY: -166.7, legRU: 70.9, legRUY: -154.8, legRF: 57.4, legRFY: 174.2 },
    ],
  },
  {
    name: 'midWide3',
    from: 'dancer 1 at 36.72s',
    poses: [
      { turn: -85.7, headTurn: 12.3, headPitch: 0.8, armLU: 2.6, armLUY: -7.3, armLF: -38.4, armLFY: 75.6, armRU: 88.1, armRUY: 156.6, armRF: 67.9, armRFY: -47, legLU: 77.3, legLUY: 174.2, legLF: 56.3, legLFY: 121.9, legRU: 82, legRUY: -166, legRF: 65.2, legRFY: 116.7 },
      { turn: -50.7, headTurn: 25.1, headPitch: -4.4, armLU: -71.6, armLUY: -100.3, armLF: -17.3, armLFY: 2.1, armRU: -25.8, armRUY: 117.5, armRF: -59.3, armRFY: 123, legLU: 77.9, legLUY: -146.4, legLF: 59.4, legLFY: 149.4, legRU: 87.4, legRUY: -46.7, legRF: 65.7, legRFY: 140.6 },
      { turn: -39, headTurn: 17.9, headPitch: -6.8, armLU: -41.5, armLUY: -92.3, armLF: -24.1, armLFY: -3.8, armRU: 59.5, armRUY: 112.3, armRF: -59.6, armRFY: -18.4, legLU: 81.7, legLUY: -138.7, legLF: 53.3, legLFY: 158.5, legRU: 85.7, legRUY: 113.1, legRF: 63.7, legRFY: 137.3 },
      { turn: -9.9, headTurn: 6.9, headPitch: 1.7, armLU: 65.8, armLUY: -60.1, armLF: 19.3, armLFY: 55.9, armRU: 85.4, armRUY: 23.3, armRF: 60.7, armRFY: -5.9, legLU: 80.4, legLUY: -68.4, legLF: 47.7, legLFY: 176.9, legRU: 86.4, legRUY: -90.6, legRF: 54, legRFY: 163.7 },
    ],
  },
  {
    name: 'midOpen',
    from: 'dancer 0 at 36.72s',
    poses: [
      { turn: -3.3, headTurn: -10, headPitch: 2.6, armLU: 40.6, armLUY: -52.8, armLF: -55.4, armLFY: 17.1, armRU: 35.7, armRUY: 32.2, armRF: -56.4, armRFY: 26.5, legLU: 77.6, legLUY: -74.7, legLF: 62.6, legLFY: -157, legRU: 74, legRUY: -129.6, legRF: 63.4, legRFY: 175.7 },
      { turn: -12.4, headTurn: -12.7, headPitch: 0.2, armLU: -56.9, armLUY: -118.1, armLF: -34.3, armLFY: 1, armRU: 23.6, armRUY: 63.7, armRF: -62.2, armRFY: -6.3, legLU: 81, legLUY: -73.8, legLF: 64.9, legLFY: -175.2, legRU: 75.7, legRUY: -138.9, legRF: 69.2, legRFY: 150.5 },
      { turn: -21.4, headTurn: -4, headPitch: 8.1, armLU: -54.7, armLUY: -118.2, armLF: -38.1, armLFY: -10.9, armRU: 24.7, armRUY: 42.9, armRF: -55.5, armRFY: 28.8, legLU: 80.5, legLUY: -51.1, legLF: 56.6, legLFY: 162.5, legRU: 69.4, legRUY: -49.9, legRF: 76.8, legRFY: 144.2 },
      { turn: 4.7, headTurn: -12.2, headPitch: 11.2, armLU: 63, armLUY: -27.6, armLF: 22.2, armLFY: 69.3, armRU: 66, armRUY: 16.2, armRF: 50, armRFY: 43.6, legLU: 80.6, legLUY: -131.8, legLF: 57.5, legLFY: -177.4, legRU: 67.9, legRUY: -108, legRF: 67.2, legRFY: 161.5 },
    ],
  },
];

export const MOVE_BY_NAME = Object.fromEntries(MOVES.map((m) => [m.name, m]));
